# Generated by Django 4.0.6 on 2022-07-17 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snakeshall', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quillpost',
            name='name',
            field=models.TextField(blank=True, default='test'),
        ),
    ]
