# Generated by Django 4.0.6 on 2022-07-17 13:27

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('snakeshall', '0002_quillpost_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quillpost',
            name='name',
        ),
        migrations.AddField(
            model_name='quillpost',
            name='admin',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='quillpost',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 7, 17, 10, 27, 46, 851253)),
        ),
        migrations.AddField(
            model_name='quillpost',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='quillpost',
            name='title',
            field=models.TextField(default=''),
        ),
    ]
