# Generated by Django 4.0.6 on 2022-07-17 13:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snakeshall', '0003_remove_quillpost_name_quillpost_admin_quillpost_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quillpost',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 7, 17, 10, 31, 56, 15948)),
        ),
    ]
