# Generated by Django 4.0.6 on 2022-07-14 18:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jungle_of_files', '0002_filepost_date_filepost_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filepost',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 7, 14, 15, 10, 43, 442158)),
        ),
        migrations.AlterField(
            model_name='filepost',
            name='image',
            field=models.FileField(blank=True, default='jof/img/default.jpg', upload_to='jof/img'),
        ),
    ]
