# Generated by Django 4.0.6 on 2022-07-15 21:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jungle_of_files', '0006_alter_filepost_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filepost',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 7, 15, 18, 11, 36, 255511)),
        ),
    ]
