# Generated by Django 4.0.6 on 2022-07-15 20:50

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('trees', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='user',
            new_name='admin',
        ),
        migrations.AddField(
            model_name='room',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 7, 15, 17, 50, 7, 89220)),
        ),
        migrations.AddField(
            model_name='room',
            name='users',
            field=models.JSONField(default='{}'),
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('date', models.DateTimeField(blank=True, default=datetime.datetime(2022, 7, 15, 17, 50, 7, 89220))),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trees.room')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
