# Generated by Django 4.0.6 on 2022-07-15 21:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trees', '0003_alter_message_date_alter_room_date_alter_room_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 7, 15, 18, 12, 14, 501029)),
        ),
        migrations.AlterField(
            model_name='room',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 7, 15, 18, 12, 14, 485408)),
        ),
        migrations.AlterField(
            model_name='room',
            name='users',
            field=models.JSONField(default='{}'),
        ),
    ]
