# Generated by Django 4.0.6 on 2022-07-15 21:25

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('trees', '0004_alter_message_date_alter_room_date_alter_room_users'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chat_message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('date', models.DateTimeField(blank=True, default=datetime.datetime(2022, 7, 15, 18, 25, 44, 464479))),
            ],
        ),
        migrations.AlterField(
            model_name='room',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 7, 15, 18, 25, 44, 464479)),
        ),
        migrations.DeleteModel(
            name='Message',
        ),
        migrations.AddField(
            model_name='chat_message',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trees.room'),
        ),
        migrations.AddField(
            model_name='chat_message',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
    ]
