# Generated by Django 4.0.6 on 2022-07-15 22:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trees', '0006_alter_chat_message_date_alter_room_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='len',
            field=models.TextField(default='lol'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='chat_message',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 7, 15, 19, 11, 28, 75881)),
        ),
        migrations.AlterField(
            model_name='room',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 7, 15, 19, 11, 28, 75881)),
        ),
    ]
